version: "0.2"
language: en
words:
  - abac
  - ABCDEFGHJKLMNPQRSTUVWXY
  - ABCDEFGHJKMNPQRSTVWXYZ
  - aboutiam
  - actions-workflow
  - active-directory
  - adfs
  - Adleman
  - adresse
  - Adresse
  - agoeb
  - AKIAEXAMPLE
  - AKIAIOSFODNN
  - alg
  - Algs
  - amara
  - ampw
  - Analyzability
  - apisec
  - apiserver
  - approle
  - AQAB
  - AQICA
  - AQID
  - ARCHS
  - ASIC
  - assertion
  - assertions
  - asym
  - attestation
  - attestationobject
  - attestations
  - aud
  - Aurl
  - authenticatordata
  - authentik
  - Authlete
  - authnrequest
  - authorization-grant-type
  - authtime
  - automount
  - autotable
  - Axiomatics
  - backchannel
  - backchannels
  - backdoors
  - backfillable
  - backqueues
  - backtest
  - balfanz
  - Balfanz
  - base58btc
  - base64url-encoded
  - base64url-encoding
  - basicauth
  - bcryptjs
  - beyondcorp
  - BEYONDCORP
  - beyondtrust
  - bff
  - birthdates
  - Blbn
  - blocklisting
  - bookmarkable
  - Bookmarkable
  - BOPIS
  - bottlenecking
  - bouncer
  - bouncer-analogy
  - bouncer-analogy-guide
  - bouncer's
  - bouncers
  - bradlc
  - Browsable
  - browser-like
  - browser-native
  - browserless
  - bruteforce
  - bsecure
  - build-ready
  - buzzings
  - bypassable
  - caep
  - capitalone
  - cbor
  - CBOR
  - ccpa
  - ccsp
  - cerbos
  - cert
  - certs
  - cfgs
  - chal
  - chall
  - check-in
  - check-off
  - check-offs
  - checklist-items
  - Checkset
  - ciam
  - ciba
  - CIBA
  - cicd
  - CIDPRO
  - ciem
  - Ciem
  - cifs
  - ciphersuite
  - CIPHERSUITES
  - ciphertext
  - CIPM
  - CIPT
  - CISA
  - CISM
  - CISO
  - cissp
  - classloader
  - clickjacking
  - Clickjacking
  - client_id
  - client_secret
  - client-side
  - clientdatajson
  - clipboard-copy
  - Cloudsplaining
  - CNSA
  - COBIT
  - code_challenge
  - code_challenge_method
  - code_verifier
  - code-exchange
  - companyorg
  - compile-ready
  - config
  - copy-to-clipboard
  - Corbató
  - CORBATO
  - corbató's
  - CPRA
  - crackable
  - createfunction
  - credential
  - credentials
  - creds
  - Creds
  - CRISC
  - crockford
  - CROCKFORD
  - Crockford
  - cross-device
  - cross-platform
  - crossborder
  - CRQC
  - cryptographical
  - cryptographically
  - cryptosystem
  - ctap
  - ctss
  - CTSS
  - curity
  - cust
  - custom-branded
  - custom-scrollbar
  - customizers
  - cutover
  - Cves
  - cyber-security
  - cyber-slate
  - cyber-slate-theme
  - cyberark
  - database-row
  - Datalog
  - datasheet
  - db_names
  - db_users
  - dbaeumer
  - dbserver
  - dcsync
  - decayer
  - decentralised
  - decodes
  - decryptions
  - Decryptor
  - deepak
  - deepfaked
  - deepfakes
  - deflate-raw
  - Delinea
  - deploy-pages
  - deprioritized
  - devsecops
  - devsecops-focused
  - Diceware
  - diceware
  - did
  - Diffie
  - DILITHIUM
  - disclosable
  - dmarc
  - DMARC
  - DMV
  - double-bolted
  - DPEHPK
  - dpop
  - drag-and-drop
  - dropdowns
  - dsig
  - DSIG
  - EAAAA
  - ecdsa
  - EDIPI
  - EDUGAIN
  - edugain
  - eidas
  - enterprise-grade
  - ents
  - Eran
  - error-free
  - ESAE
  - esbenp
  - EUDI
  - Evilginx
  - exfil
  - exfiltratable
  - exfiltrated
  - exfiltrates
  - exfiltrating
  - Exfiltration
  - exfiltration
  - exhaustedly
  - exp
  - expressjwt
  - extn
  - Falco
  - fapi
  - Fapi
  - fedramp
  - FERPA
  - FHIR
  - fhir
  - fido2
  - FIDO2
  - financials
  - finegrained
  - fintech
  - Fintech
  - fintechs
  - FIPS
  - firewalling
  - footguns
  - forceauthn
  - forgeability
  - forgerock
  - Forrester
  - freeipa
  - Freemarker
  - front-channel
  - frontchannel
  - Frontegg
  - frontegg
  - full-stack
  - full-stack-developer
  - fullchain
  - fusionauth
  - Gamified
  - gapi
  - gatekeeping
  - gatekeepings
  - generatable
  - geoblock
  - Geoblock
  - Geoblocking
  - geofence
  - geofenced
  - geofencing
  - geolocation
  - geolocations
  - geovelocity
  - getstartup
  - GHSA
  - ghsa
  - giscus
  - Giscus
  - GISCUS
  - git-push
  - gitops
  - glovebox
  - gmsa
  - gnap
  - GNAP
  - gnolia
  - goauthentik
  - godaddy
  - godaddy's
  - goldensaml
  - googleusercontent
  - gpos
  - Halff
  - hand-crafted
  - Hardt
  - header-headers
  - Heimdal
  - héllo
  - helpdesk
  - hibp
  - high-contrast
  - high-entropy
  - high-fidelity
  - HJKMNP
  - hmac
  - hmr
  - homelab
  - hot-reloading
  - hotp
  - HOTP
  - hover-reactive
  - HRIS
  - httponly
  - httpsig
  - IAPP
  - iat
  - idaas
  - IDAS
  - idcloud
  - identity-first
  - identitynow
  - Identiverse
  - Idira
  - idira
  - IDOR
  - idps
  - IDPSSO
  - idsa
  - Ijoxf
  - imtp
  - Imtp
  - Infinispan
  - infostealer
  - infostealers
  - inspectable
  - interfederation
  - Interfederation
  - Interledger
  - Intune
  - iram
  - ISACA
  - iscompromised
  - iss
  - itdr
  - Itdr
  - ITDR
  - Jaccard
  - jaccard
  - jailbroken
  - jaiswal
  - Jamf
  - JARM
  - JBSWY
  - jdoe
  - jjwt
  - jku
  - JNDI
  - jndi
  - Jndi
  - jspdf
  - jumpcloud
  - jwe
  - jwk
  - jwks
  - jws
  - jwt
  - jwt_payload
  - jwt_secret
  - jwth
  - jwtp
  - jwts
  - kantara
  - kbheader
  - kbpayload
  - kbsig
  - KDC
  - KDCs
  - kerberoasted
  - Kerberoasting
  - kerbtier
  - keycards
  - keycloak
  - keyhole
  - keylogging
  - keypair
  - keypairs
  - keyphrase
  - keyspace
  - keystroke
  - keystrokes
  - keytabs
  - kfpao
  - kid
  - kinit
  - Kostenstelle
  - Kqqw
  - Kratos
  - kratos
  - krbtgt
  - KRBTGT
  - ktapus
  - kubeconfig
  - Kubelet
  - kubelet
  - Kuppinger
  - kuppingercole
  - LAEB
  - lastmod
  - lastmodified
  - lastpass
  - LASTPASS
  - Lclc
  - ldapad
  - ldapadd
  - ldapjs
  - LDAPS
  - ldaps
  - ldapv
  - LDIF
  - ldif
  - lifecycle
  - lifecycles
  - linkability
  - LJXZ
  - llms
  - lnbm
  - Lockdown
  - lockdowns
  - long-lived
  - low-fidelity
  - LSASS
  - lucide
  - Lukas
  - LXBs
  - mailroom
  - mailrooms
  - Maler
  - MASTERSECTION
  - maturity-score
  - maturity-scores
  - mayank
  - mayankrajjaiswal
  - MCQS
  - mcqs
  - Melhoa
  - MEUCIQ
  - mfa
  - MFA
  - Mgmt
  - micro-interactions
  - Microsegmentation
  - microsegmentation
  - microservices
  - microsoftonline
  - MIIB
  - Mimikatz
  - mindshare
  - minisearch
  - miscalibrated
  - Mishra
  - misordered
  - mkhomedir
  - MLDSA
  - MLKEM
  - Modbus
  - mortems
  - Moscone
  - moveit
  - MOVWGLJ
  - msal
  - multi-choice
  - multi-cloud
  - multi-contributor
  - multi-pillar
  - multi-step
  - multi-tenancy
  - multi-tenant
  - multibase
  - multicodec
  - Multikey
  - multitenant
  - multivalued
  - Mvzy
  - nachname
  - Nachname
  - namecheap
  - nameid
  - Nandakumar
  - nciphertext
  - NERUZH
  - netlify
  - Netlogon
  - NETLOGON
  - neuman
  - Neuman
  - nexecve
  - nextjs
  - Nlcl
  - non-human
  - non-human-identities
  - non-human-identity
  - none-alg
  - none-algorithm
  - noout
  - nosniff
  - notpetya
  - NTDS
  - ntlm
  - nufw
  - NYCRR
  - Oathkeeper
  - oauthbp
  - objectclass
  - OCSP
  - OFAC
  - OGNL
  - Ognl
  - oidc
  - OIDC
  - OIDF
  - OIDS
  - Okabe
  - Okafor
  - oktahar
  - Oktane
  - Omada
  - Omnichannel
  - onelogin
  - onewelcome
  - onprem
  - OPA
  - OPAs
  - open-source-project
  - open-source-ready
  - openbadges
  - openidconnect
  - organigram
  - OSCP
  - OSWE
  - otpauth
  - outpost
  - outposts
  - outposts-proxy
  - overprivilege
  - padlock
  - Palo
  - panva
  - paper-white
  - parecki
  - parent
  - parsejwt
  - partialize
  - PASETO
  - paseto
  - passkey
  - passkey-authentication
  - passkey-registration
  - passkeys
  - passrole
  - passsess
  - passwordless
  - Pasteable
  - pathlen
  - pdf-export
  - pdp
  - PDP
  - PEAP
  - Pentester
  - pep
  - PEP
  - personalnummer
  - Personalnummer
  - Personalwesen
  - Petrova
  - Petya
  - Phishable
  - phishable
  - physical-person
  - physics-based
  - pingfederate
  - pingone
  - pip
  - PIP
  - pixel-perfect
  - pkce
  - PKCE
  - PKCE's
  - pkcs10
  - pkcs8
  - PKIX
  - platform-proof
  - playbooks
  - playwight
  - porkbun
  - porkbun's
  - postbuild
  - postdates
  - Prateek
  - Preconfigurations
  - preimage
  - Priya
  - priya
  - production-ready
  - prompt-bombing
  - promptless
  - proxy-pass
  - pseudonymization
  - Pseudonymization
  - psexec
  - push-bombing
  - push-fatigue
  - pushfatigue
  - PVWA
  - pyjwt
  - pypi
  - qubits
  - quickstarts
  - Qwen
  - qwww
  - raci
  - Raci
  - RACI
  - Rajat
  - rajat
  - Rastogi
  - ravi
  - real-world
  - rebac
  - ReBAC
  - rebranded
  - recertification
  - Recertification
  - recertify
  - redirect_uri
  - redirect-uri
  - redirect-uris
  - redirections
  - rego
  - Regos
  - remediations
  - remeditations
  - replayable
  - researchable
  - response_type
  - RFID
  - Rivest
  - roadmap-check
  - rockyou
  - rolebinding
  - rolldown
  - rollouts
  - RPID
  - RSAC
  - rubygems
  - rulebook
  - runas
  - runinstances
  - saasapp
  - SAFENET
  - sailpoint
  - samesite
  - saml
  - SAML
  - samlify
  - samlp
  - samlresponse
  - SASL
  - Saviynt
  - scen
  - SCHERR
  - Scherr
  - scim
  - SCIM
  - scrollbar
  - secops
  - Sectigo
  - Secur
  - secure-challenge
  - securid
  - security-centric
  - security-focused
  - self-assessment
  - self-destructing
  - self-hosted
  - self-sovereign
  - self-sovereign-identity
  - server-side
  - serviceaccount
  - sfla
  - shackle
  - Shamir
  - Sharma
  - sharma
  - Shellshock
  - Shodan
  - Shor's
  - short-lived
  - shufflings
  - siem
  - signature-exclusions
  - signature-wrapping
  - signups
  - silversaml
  - simplewebauthn
  - single-page
  - single-page-app
  - siop
  - SIOP
  - sitel
  - Sitel
  - SLHDSA
  - Slugifies
  - smartcard
  - Smartcards
  - smartcards
  - Smol
  - sname
  - snark
  - snarks
  - sniffable
  - spacewar
  - SPHINCS
  - spiffe
  - spire
  - spki
  - splittable
  - Splxl
  - SPNEGO
  - spof
  - spoofable
  - springboot
  - springframework
  - SPSSO
  - ssf
  - sso
  - SSO
  - sspiffe
  - sspire
  - SSPR
  - sspr
  - SSTC
  - ssvid
  - ssw
  - standardly
  - startup-friendly
  - state-management
  - state-of-the-art
  - statecreator
  - status-badge
  - statusbar
  - stix
  - Stix
  - STIX
  - Strivacity
  - Strivacity's
  - structured-data
  - Stuxnet
  - Styra
  - sub
  - subdirectories
  - sublimits
  - submodules
  - subprocessor
  - Subprocessor
  - subprocessors
  - Subtab
  - subtabs
  - Supabase
  - superadmin
  - supersecretpassword
  - svg-export
  - svid
  - svids
  - Sxip
  - Syncer
  - szyn
  - TACACS
  - Tacacs
  - tamperable
  - taxii
  - Taxii
  - TAXII
  - telco
  - telehealth
  - time-based
  - time-of-day
  - toolsets
  - totp
  - TOTP
  - transpiles
  - Trinsic
  - trojanized
  - TRUNSRV
  - ttcp
  - typ
  - type-safe
  - typesafe
  - UEBA
  - ulid
  - ULID
  - unalterable
  - unbrokered
  - unclustered
  - unconfigured
  - uncopyable
  - unforgeable
  - unhash
  - unhashed
  - unmemoized
  - unpad
  - unpadded
  - unpadding
  - unparseable
  - Unredacted
  - unredacted
  - unreviewed
  - unrevocable
  - unrotated
  - unstub
  - unvalidated
  - unvault
  - Unvault
  - upserts
  - urlsafe
  - usecases
  - user-friendly
  - user-verification
  - userinfo
  - utility-first
  - varint
  - vaulttext
  - Veramo
  - verifyjwt
  - vermillion
  - Vertrieb
  - Vggv
  - viewbox
  - viewports
  - visual-first
  - vite
  - vitest
  - Vnca
  - vorname
  - Vorname
  - VSSUZJRVI
  - warm-gray
  - warning-free
  - watchlist
  - WAYF
  - Wayf
  - wayf
  - WCDB
  - webapi
  - webauthn
  - webauthn's
  - webkit
  - webllm
  - webroot
  - Wessels
  - widescreen
  - wildcarding
  - wildfly
  - Wireshark
  - wkst
  - WKST
  - wordcount
  - Wordle
  - Wordlist
  - WORKBUNCH
  - workos
  - writeback
  - writeups
  - Writeups
  - wrongpassword
  - wxyz
  - XACML
  - xacml
  - Xacml
  - Xktdj
  - XMLD
  - xmlsig
  - XVCJ
  - yasmin
  - Yastogi
  - Yemi
  - yourcompany
  - yoursheet
  - yourtype
  - yubi
  - Yubico
  - yubikey
  - yubikeys
  - Zabcdefghijkmnopqrstuvwxyz
  - zack
  - zero-backend
  - zero-cost
  - zero-knowledge
  - zero-knowledge-proof
  - Zerologon
  - Zitadel
  - zkp
  - zkps
  - zta
  - ZTA
  - ZTNA
  - ztna
  - zustand
