import { describe, it, expect } from 'vitest'
import { readFileSync } from 'node:fs'
import { join } from 'node:path'
import { ROUTE_META } from '../../src/routeMeta'
import { TOOLS } from '../../src/data/toolsRegistry'
import { buildSitemapUrls } from '../../scripts/generate-sitemap'

// public/sitemap.xml, public/llms.txt, and public/rss.xml are committed
// "dev-copy/fallback-source" build artifacts (per GEMINI.md's documented
// convention) regenerated by `npm run build` from ROUTE_META/TOOLS — but
// `npm run test` never runs the build, so a contributor who commits a new
// page/tool without running a full build leaves these files stale. This has
// happened twice already (caught only by manually diffing after the fact) —
// this suite catches it automatically instead, without needing to re-run the
// actual generator scripts.
const repoRoot = join(__dirname, '..', '..')

describe('committed public/ build artifacts are not stale relative to their source registries', () => {
  it('public/sitemap.xml has exactly one <url> entry per generated sitemap URL', () => {
    const sitemap = readFileSync(join(repoRoot, 'public', 'sitemap.xml'), 'utf-8')
    const urlCount = (sitemap.match(/<url>/g) ?? []).length
    const expectedCount = buildSitemapUrls(ROUTE_META).length
    expect(urlCount, 'run `npm run build` (or `node --experimental-strip-types scripts/generate-sitemap.ts`) to refresh public/sitemap.xml').toBe(expectedCount)
  })

  it('public/llms.txt links every ROUTE_META route', () => {
    const llms = readFileSync(join(repoRoot, 'public', 'llms.txt'), 'utf-8')
    const missing = ROUTE_META.filter((r) => {
      const normalizedPath = r.path === '/' ? '' : r.path.replace(/\/+$/, '')
      return !llms.includes(`(https://www.aboutiam.com${normalizedPath}/)`)
    })
    expect(missing.map((r) => r.path), 'run `npm run build` to refresh public/llms.txt').toEqual([])
  })

  it('public/rss.xml includes every live tool from toolsRegistry.ts', () => {
    const rss = readFileSync(join(repoRoot, 'public', 'rss.xml'), 'utf-8')
    const missingLiveTools = TOOLS.filter((t) => t.status === 'live' && !rss.includes(`/tools/${t.slug}`))
    expect(missingLiveTools.map((t) => t.slug), 'run `npm run build` to refresh public/rss.xml').toEqual([])
  })
})
