import { describe, it, expect } from 'vitest'
import { signCertificate, verifyCertificate, type CertificatePayload } from './certificateSigner'

const BASE_PAYLOAD: CertificatePayload = {
  recipientName: 'Ada Lovelace',
  completedModuleCount: 24,
  totalModuleCount: 36,
  completedLabCount: 8,
  issuedOn: '2026-07-31',
  certificateId: 'cert-0001',
}

describe('certificateSigner', () => {
  it('a certificate generated by the signing logic verifies successfully', async () => {
    const signed = await signCertificate(BASE_PAYLOAD)
    expect(await verifyCertificate(signed)).toBe(true)
  })

  it('a tampered payload (one field changed) fails verification', async () => {
    const signed = await signCertificate(BASE_PAYLOAD)
    const tampered = { ...signed, payload: { ...signed.payload, completedModuleCount: 36 } }
    expect(await verifyCertificate(tampered)).toBe(false)
  })

  it('a tampered recipient name fails verification', async () => {
    const signed = await signCertificate(BASE_PAYLOAD)
    const tampered = { ...signed, payload: { ...signed.payload, recipientName: 'Someone Else' } }
    expect(await verifyCertificate(tampered)).toBe(false)
  })

  it('a tampered signature fails verification', async () => {
    const signed = await signCertificate(BASE_PAYLOAD)
    const tampered = { ...signed, signature: signed.signature.slice(0, -4) + 'abcd' }
    expect(await verifyCertificate(tampered)).toBe(false)
  })

  it('a malformed/garbage certificate fails verification instead of throwing', async () => {
    const result = await verifyCertificate({
      payload: BASE_PAYLOAD,
      signature: 'not-a-real-signature',
      publicKeyJwk: { kty: 'EC' },
    })
    expect(result).toBe(false)
  })

  it('two certificates for different payloads produce different signatures', async () => {
    const signedA = await signCertificate(BASE_PAYLOAD)
    const signedB = await signCertificate({ ...BASE_PAYLOAD, completedModuleCount: 30 })
    expect(signedA.signature).not.toBe(signedB.signature)
  })
})
