import { useState } from 'react'
import { Link } from 'react-router-dom'
import { 
  ShieldAlert, ShieldCheck, ArrowRight, RefreshCw, 
  Terminal, HelpCircle, Play, Check, Copy
} from 'lucide-react'

type AttackScenario = 'pkce_bypass' | 'redirect_wildcard' | 'csrf_state'

export default function OAuthAttackLab() {
  const [scenario, setScenario] = useState<AttackScenario>('pkce_bypass')
  
  // Exploit vs Remediation Toggles
  const [pkceEnabled, setPkceEnabled] = useState(false)
  const [exactRedirectMatch, setExactRedirectMatch] = useState(false)
  const [stateValidationEnabled, setStateValidationEnabled] = useState(false)

  // Simulation States
  const [simStep, setSimStep] = useState<number>(0)
  const [attackLogs, setAttackLogs] = useState<string[]>([])
  const [copiedText, setCopiedText] = useState<string | null>(null)
  
  // Scenario-specific states
  const [interceptedCode] = useState<string>('auth_code_9a8b7c')
  const [attackerReceivedToken, setAttackerReceivedToken] = useState<string | null>(null)
  const [victimLinkedToAttacker, setVictimLinkedToAttacker] = useState<boolean | null>(null)

  const addLog = (msg: string) => {
    setAttackLogs(prev => [...prev, `[${new Date().toLocaleTimeString()}] ${msg}`])
  }

  const resetSimulator = () => {
    setSimStep(0)
    setAttackLogs([])
    setAttackerReceivedToken(null)
    setVictimLinkedToAttacker(null)
  }

  const handleScenarioChange = (scen: AttackScenario) => {
    setScenario(scen)
    resetSimulator()
  }

  const handleCopy = (text: string, id: string) => {
    navigator.clipboard.writeText(text)
    setCopiedText(id)
    setTimeout(() => setCopiedText(null), 1500)
  }

  // --- SCENARIO 1: PKCE BYPASS SIMULATION ---
  const runPkceStep1 = () => {
    addLog(`SPA App initiates login. PKCE Status: ${pkceEnabled ? 'ENABLED' : 'DISABLED'}`)
    if (pkceEnabled) {
      addLog(`Generated parameters: code_verifier="SUpFUl9TRUNSRVRfVkVSSUZJRVI..."`)
      addLog(`Computed S256 challenge: code_challenge="xyz123_abc456..."`)
    } else {
      addLog(`⚠️ Warning: No code_challenge or verifier generated by client application!`)
    }
    setSimStep(1)
  }

  const runPkceStep2 = () => {
    addLog(`User completes authentication in browser against IdP.`)
    addLog(`IdP issues temporary authorization code via frontchannel redirect: ?code=${interceptedCode}`)
    addLog(`🚨 Attacker malware intercepts custom protocol handler (aboutiam-app://) and steals code!`)
    setSimStep(2)
  }

  const runPkceStep3 = () => {
    addLog(`Attacker attempts to redeem the stolen code at the token endpoint /oauth/token`)
    
    if (pkceEnabled) {
      addLog(`❌ Server checks for matching code_verifier. Attacker does not know the raw code_verifier!`)
      addLog(`Server rejects request with HTTP 400 Bad Request: "invalid_grant" (failed PKCE verification).`)
      setAttackerReceivedToken('REJECTED')
      addLog(`🛡️ Secure Defense: PKCE blocked the attacker from obtaining the Access Token!`)
    } else {
      addLog(`Server sees no code_challenge registered in authorization step. Code verification is skipped.`)
      addLog(`Server issues access token to attacker!`)
      setAttackerReceivedToken('at_attacker_compromised_token_8828c')
      addLog(`🔓 Breach! Attacker has acquired full API credentials for the victim.`)
    }
    setSimStep(3)
  }

  // --- SCENARIO 2: REDIRECT URI WILDCARD MATCHING ---
  const runRedirectStep1 = () => {
    addLog(`Attacker delivers a phishing link to the victim:`)
    const maliciousUri = exactRedirectMatch 
      ? `https://aboutiam.com/callback` 
      : `https://aboutiam.com/callback?redirect_to=https://attacker-server.com/collect`
    addLog(`Auth Link: /authorize?client_id=my-app&redirect_uri=${maliciousUri}`)
    setSimStep(1)
  }

  const runRedirectStep2 = () => {
    addLog(`Victim clicks link and authenticates securely against the Authorization Server.`)
    if (exactRedirectMatch) {
      addLog(`❌ Server rejects the request! Exact redirect URI matching is enabled. The parameter does not match the strict whitelist string.`)
      setSimStep(3)
      setAttackerReceivedToken('REJECTED')
    } else {
      addLog(`Server performs loose wildcard validation: "https://aboutiam.com/*" matched correctly.`)
      addLog(`Server redirects browser carrying access token in fragment: #access_token=at_secret_token_12`)
      addLog(`🚨 Victim browser loads the landing page callback, which contains an open-redirect to the malicious server.`)
      setSimStep(2)
    }
  }

  const runRedirectStep3 = () => {
    addLog(`Attacker server receives referrer header containing the full URL fragment!`)
    addLog(`🚨 Captured Token: "at_secret_token_12" recorded in attacker logs.`)
    setAttackerReceivedToken('at_secret_token_12')
    setSimStep(3)
  }

  // --- SCENARIO 3: CSRF STATE OMISSION ---
  const runCsrfStep1 = () => {
    addLog(`Attacker clicks "Link Bank Account" in the client app.`)
    addLog(`Attacker intercepts their own callback redirect before it processes: /callback?code=attacker_code_771`)
    addLog(`Attacker prepares an exploit page embedding this URL and delivers it to the victim.`)
    setSimStep(1)
  }

  const runCsrfStep2 = () => {
    addLog(`Victim (logged in) clicks the attacker's link.`)
    addLog(`Victim's browser requests the callback: /callback?code=attacker_code_771&state=attacker_state_445`)
    
    if (stateValidationEnabled) {
      addLog(`Server check: Session expects state="victim_session_state_992" but received state="attacker_state_445"`)
      addLog(`❌ Session mismatch! Server rejects callback processing due to state/CSRF validation failure.`)
      setVictimLinkedToAttacker(false)
    } else {
      addLog(`No state parameter validated. Server processes callback: codes are swapped.`)
      addLog(`SaaS server binds the attacker's credential context to the victim's local browser profile!`)
      setVictimLinkedToAttacker(true)
      addLog(`🚨 Breach! Victim is now linking their data directly to the attacker's backend resources!`)
    }
    setSimStep(2)
  }

  return (
    <div className="min-h-screen bg-bg-base text-text-primary font-sans">
      {/* Upper Navigation Header */}
      <div className="border-b border-border-subtle bg-bg-card px-6 py-4 flex items-center justify-between">
        <div className="flex items-center gap-3">
          <ShieldAlert className="text-status-danger w-6 h-6 animate-pulse" />
          <div>
            <h1 className="text-lg font-bold tracking-tight">OAuth 2.0 / OIDC Attack Lab</h1>
            <p className="text-xs text-text-secondary">Interactive arena for exploring common token flow vulnerabilities & mitigation scripts</p>
          </div>
        </div>
        <Link to="/playground" className="text-sm bg-bg-nested hover:bg-border-subtle px-3 py-1.5 rounded text-text-secondary flex items-center gap-1.5 transition">
          <ArrowRight className="rotate-180 w-4 h-4" /> Back to Catalog
        </Link>
      </div>

      {/* Main Container Grid */}
      <div className="p-6 max-w-7xl mx-auto grid grid-cols-1 lg:grid-cols-12 gap-6">
        
        {/* Left column: Controls & Exploits */}
        <div className="lg:col-span-5 flex flex-col gap-6">
          {/* Scenario Selector */}
          <div className="bg-bg-card border border-border-subtle rounded-xl p-5 shadow-lg">
            <h2 className="font-semibold text-sm text-text-primary uppercase tracking-wider mb-3">Select Vulnerability Scenario</h2>
            <div className="space-y-2">
              <button 
                onClick={() => handleScenarioChange('pkce_bypass')}
                className={`w-full text-left p-3 rounded-lg border text-xs flex flex-col gap-1 transition ${scenario === 'pkce_bypass' ? 'bg-status-danger/10 border-status-danger/45 text-status-danger' : 'bg-bg-nested/40 border-border-subtle text-text-secondary hover:border-border-subtle'}`}
              >
                <span className="font-bold flex items-center gap-2">
                  <span className={`w-2 h-2 rounded-full ${scenario === 'pkce_bypass' ? 'bg-status-danger' : 'bg-text-muted'}`}></span>
                  1. Authorization Code Interception (No PKCE)
                </span>
                <span>Visualizes native app code theft where lack of proof key validation allows code reuse.</span>
              </button>

              <button 
                onClick={() => handleScenarioChange('redirect_wildcard')}
                className={`w-full text-left p-3 rounded-lg border text-xs flex flex-col gap-1 transition ${scenario === 'redirect_wildcard' ? 'bg-status-danger/10 border-status-danger/45 text-status-danger' : 'bg-bg-nested/40 border-border-subtle text-text-secondary hover:border-border-subtle'}`}
              >
                <span className="font-bold flex items-center gap-2">
                  <span className={`w-2 h-2 rounded-full ${scenario === 'redirect_wildcard' ? 'bg-status-danger' : 'bg-text-muted'}`}></span>
                  2. Open Redirect / Wildcard Whitelisting
                </span>
                <span>Explores how loose redirect string evaluation permits theft of tokens in referrer logs.</span>
              </button>

              <button 
                onClick={() => handleScenarioChange('csrf_state')}
                className={`w-full text-left p-3 rounded-lg border text-xs flex flex-col gap-1 transition ${scenario === 'csrf_state' ? 'bg-status-danger/10 border-status-danger/45 text-status-danger' : 'bg-bg-nested/40 border-border-subtle text-text-secondary hover:border-border-subtle'}`}
              >
                <span className="font-bold flex items-center gap-2">
                  <span className={`w-2 h-2 rounded-full ${scenario === 'csrf_state' ? 'bg-status-danger' : 'bg-text-muted'}`}></span>
                  3. CSRF / State Parameter Omission
                </span>
                <span>Shows account linking hijack where missing state parameters allow forced logins.</span>
              </button>
            </div>
          </div>

          {/* Defense Policy Box */}
          <div className="bg-bg-card border border-border-subtle rounded-xl p-5 shadow-lg">
            <h2 className="font-semibold text-sm text-text-primary uppercase tracking-wider mb-3">Defensive Mitigations</h2>
            
            {scenario === 'pkce_bypass' && (
              <div className="space-y-4">
                <p className="text-xs text-text-secondary">
                  Toggle the security settings below to test how the system reacts to an interception attack.
                </p>
                <div className="flex items-center justify-between p-3 bg-bg-base border border-border-subtle rounded-lg">
                  <div>
                    <span className="block text-xs font-bold text-text-primary">Enable PKCE (RFC 7636)</span>
                    <span className="text-[10px] text-text-muted">Force SHA-256 verifier matching during token exchange</span>
                  </div>
                  <button 
                    onClick={() => { setPkceEnabled(!pkceEnabled); resetSimulator() }}
                    className={`px-3 py-1.5 rounded text-xs font-bold transition ${pkceEnabled ? 'bg-status-success hover:bg-status-success/95 text-white' : 'bg-bg-nested hover:bg-border-subtle text-text-secondary'}`}
                  >
                    {pkceEnabled ? 'SECURE' : 'VULNERABLE'}
                  </button>
                </div>
              </div>
            )}

            {scenario === 'redirect_wildcard' && (
              <div className="space-y-4">
                <p className="text-xs text-text-secondary">
                  Enable strict security validation checks on redirect URLs to prevent open forwarding parameters.
                </p>
                <div className="flex items-center justify-between p-3 bg-bg-base border border-border-subtle rounded-lg">
                  <div>
                    <span className="block text-xs font-bold text-text-primary">Strict Redirect URI Match</span>
                    <span className="text-[10px] text-text-muted">Reject wildcard queries or path parameters</span>
                  </div>
                  <button 
                    onClick={() => { setExactRedirectMatch(!exactRedirectMatch); resetSimulator() }}
                    className={`px-3 py-1.5 rounded text-xs font-bold transition ${exactRedirectMatch ? 'bg-status-success hover:bg-status-success/95 text-white' : 'bg-bg-nested hover:bg-border-subtle text-text-secondary'}`}
                  >
                    {exactRedirectMatch ? 'SECURE' : 'VULNERABLE'}
                  </button>
                </div>
              </div>
            )}

            {scenario === 'csrf_state' && (
              <div className="space-y-4">
                <p className="text-xs text-text-secondary">
                  Require state binding inside the user browser session to prevent forced callback injection.
                </p>
                <div className="flex items-center justify-between p-3 bg-bg-base border border-border-subtle rounded-lg">
                  <div>
                    <span className="block text-xs font-bold text-text-primary">Validate state parameter</span>
                    <span className="text-[10px] text-text-muted">Force browser session token correlation checks</span>
                  </div>
                  <button 
                    onClick={() => { setStateValidationEnabled(!stateValidationEnabled); resetSimulator() }}
                    className={`px-3 py-1.5 rounded text-xs font-bold transition ${stateValidationEnabled ? 'bg-status-success hover:bg-status-success/95 text-white' : 'bg-bg-nested hover:bg-border-subtle text-text-secondary'}`}
                  >
                    {stateValidationEnabled ? 'SECURE' : 'VULNERABLE'}
                  </button>
                </div>
              </div>
            )}
          </div>
        </div>

        {/* Right column: Simulation Canvas & Arena */}
        <div className="lg:col-span-7 flex flex-col gap-6">
          {/* Interactive Flow Visualizer */}
          <div className="bg-bg-card border border-border-subtle rounded-xl p-5 shadow-lg flex flex-col min-h-[380px] justify-between">
            <div>
              <div className="flex justify-between items-center mb-4">
                <h2 className="font-semibold text-sm text-text-primary flex items-center gap-1.5">
                  <Play className="w-4 h-4 text-accent-primary fill-current" /> Simulation Board
                </h2>
                <button 
                  onClick={resetSimulator}
                  className="text-xs text-text-secondary hover:text-text-primary flex items-center gap-1 bg-bg-nested border border-border-subtle px-2.5 py-1.5 rounded transition"
                >
                  <RefreshCw className="w-3 h-3" /> Reset Flow
                </button>
              </div>

              {/* --- SCENARIO 1: PKCE BOARD --- */}
              {scenario === 'pkce_bypass' && (
                <div className="space-y-6">
                  <div className="relative border border-border-subtle bg-bg-base rounded-xl p-4 grid grid-cols-3 gap-4 items-center">
                    <div className="text-center">
                      <div className="bg-accent-glow text-accent-primary border border-accent-primary/20 p-2.5 rounded-lg text-xs font-bold">
                        Client SPA
                      </div>
                      <span className="text-[9px] text-text-muted block mt-1">Legitimate Client</span>
                    </div>

                    <div className="flex justify-center flex-col items-center">
                      <div className="w-full h-0.5 bg-border-subtle relative">
                        {simStep === 1 && (
                          <div className="w-2.5 h-2.5 bg-status-warning rounded-full absolute top-1/2 -translate-y-1/2 left-0 animate-ping"></div>
                        )}
                      </div>
                      <span className="text-[9px] text-text-muted mt-1">Interception Pipeline</span>
                    </div>

                    <div className="text-center">
                      <div className="bg-status-danger/10 text-status-danger border border-status-danger/30 p-2.5 rounded-lg text-xs font-bold animate-pulse">
                        Malware Script
                      </div>
                      <span className="text-[9px] text-status-danger block mt-1">Intercepts Code URI</span>
                    </div>
                  </div>

                  {/* Interactive step trigger buttons */}
                  <div className="grid grid-cols-3 gap-3">
                    <button 
                      onClick={runPkceStep1} 
                      disabled={simStep !== 0}
                      className={`py-2 px-3 rounded-lg text-xs font-bold border transition text-center ${simStep === 0 ? 'bg-accent-primary hover:bg-accent-hover text-white border-accent-primary' : 'bg-bg-nested text-text-muted border-border-subtle cursor-not-allowed'}`}
                    >
                      Step 1: Init Authorization
                    </button>

                    <button 
                      onClick={runPkceStep2} 
                      disabled={simStep !== 1}
                      className={`py-2 px-3 rounded-lg text-xs font-bold border transition text-center ${simStep === 1 ? 'bg-status-warning hover:bg-status-warning/95 text-white border-status-warning/40' : 'bg-bg-nested text-text-muted border-border-subtle cursor-not-allowed'}`}
                    >
                      Step 2: Intercept Code
                    </button>

                    <button 
                      onClick={runPkceStep3} 
                      disabled={simStep !== 2}
                      className={`py-2 px-3 rounded-lg text-xs font-bold border transition text-center ${simStep === 2 ? 'bg-status-danger hover:bg-status-danger/95 text-white border-status-danger/40 animate-pulse' : 'bg-bg-nested text-text-muted border-border-subtle cursor-not-allowed'}`}
                    >
                      Step 3: Swap Code
                    </button>
                  </div>
                </div>
              )}

              {/* --- SCENARIO 2: REDIRECT WILDCARD BOARD --- */}
              {scenario === 'redirect_wildcard' && (
                <div className="space-y-6">
                  <div className="border border-border-subtle bg-bg-base rounded-xl p-4 flex flex-col gap-3">
                    <span className="text-[10px] font-bold text-text-muted uppercase tracking-wider block">OAuth Client Configuration Whitelist</span>
                    <div className="flex gap-2">
                      <span className="text-xs bg-accent-glow border border-accent-primary/20 px-2 py-1 rounded text-accent-primary font-mono">
                        {exactRedirectMatch ? 'https://aboutiam.com/callback' : 'https://aboutiam.com/*'}
                      </span>
                      {!exactRedirectMatch && (
                        <span className="text-[10px] font-bold bg-status-danger/10 text-status-danger border border-status-danger/30 px-2 py-1 rounded animate-pulse">
                          ⚠️ Loose Wildcard Whitelisted!
                        </span>
                      )}
                    </div>
                  </div>

                  <div className="grid grid-cols-3 gap-3">
                    <button 
                      onClick={runRedirectStep1} 
                      disabled={simStep !== 0}
                      className={`py-2 px-3 rounded-lg text-xs font-bold border transition text-center ${simStep === 0 ? 'bg-status-danger hover:bg-status-danger/95 text-white border-status-danger/40' : 'bg-bg-nested text-text-muted border-border-subtle cursor-not-allowed'}`}
                    >
                      Step 1: Deliver Link
                    </button>

                    <button 
                      onClick={runRedirectStep2} 
                      disabled={simStep !== 1}
                      className={`py-2 px-3 rounded-lg text-xs font-bold border transition text-center ${simStep === 1 ? 'bg-status-danger hover:bg-status-danger/95 text-white border-status-danger/40' : 'bg-bg-nested text-text-muted border-border-subtle cursor-not-allowed'}`}
                    >
                      Step 2: Trigger Redirect
                    </button>

                    <button 
                      onClick={runRedirectStep3} 
                      disabled={simStep !== 2}
                      className={`py-2 px-3 rounded-lg text-xs font-bold border transition text-center ${simStep === 2 ? 'bg-status-danger hover:bg-status-danger/95 text-white border-status-danger/40 animate-pulse' : 'bg-bg-nested text-text-muted border-border-subtle cursor-not-allowed'}`}
                    >
                      Step 3: Collect Token
                    </button>
                  </div>
                </div>
              )}

              {/* --- SCENARIO 3: CSRF STATE OMISSION --- */}
              {scenario === 'csrf_state' && (
                <div className="space-y-6">
                  <div className="bg-bg-base border border-border-subtle rounded-xl p-4 text-xs space-y-2">
                    <span className="font-bold text-text-secondary block mb-1">Session Context Variables</span>
                    <div className="grid grid-cols-2 gap-3 text-[11px] font-mono">
                      <div className="bg-bg-card p-2 rounded border border-border-subtle">
                        <span className="block text-text-muted text-[10px]">Browser Session state:</span>
                        <span className="text-accent-secondary">victim_session_state_992</span>
                      </div>
                      <div className="bg-bg-card p-2 rounded border border-border-subtle">
                        <span className="block text-text-muted text-[10px]">Incoming Callback state:</span>
                        <span className={simStep >= 1 ? 'text-status-warning' : 'text-text-muted'}>
                          {simStep >= 1 ? 'attacker_state_445' : 'Pending...'}
                        </span>
                      </div>
                    </div>
                  </div>

                  <div className="grid grid-cols-2 gap-3">
                    <button 
                      onClick={runCsrfStep1} 
                      disabled={simStep !== 0}
                      className={`py-2 px-3 rounded-lg text-xs font-bold border transition text-center ${simStep === 0 ? 'bg-accent-primary hover:bg-accent-hover text-white border-accent-primary' : 'bg-bg-nested text-text-muted border-border-subtle cursor-not-allowed'}`}
                    >
                      Step 1: Attacker Forges Link
                    </button>

                    <button 
                      onClick={runCsrfStep2} 
                      disabled={simStep !== 1}
                      className={`py-2 px-3 rounded-lg text-xs font-bold border transition text-center ${simStep === 1 ? 'bg-status-danger hover:bg-status-danger/95 text-white border-status-danger/40 animate-pulse' : 'bg-bg-nested text-text-muted border-border-subtle cursor-not-allowed'}`}
                    >
                      Step 2: Victim Clicks & Links
                    </button>
                  </div>
                </div>
              )}

              {/* Status Outcome Banner */}
              <div className="mt-6 pt-4 border-t border-border-subtle">
                {attackerReceivedToken && (
                  attackerReceivedToken === 'REJECTED' ? (
                    <div className="bg-status-success/15 text-status-success border border-status-success/30 p-4 rounded-xl flex items-start gap-3">
                      <ShieldCheck className="w-5 h-5 text-status-success shrink-0 mt-0.5 animate-bounce" />
                      <div>
                        <span className="font-extrabold text-sm block">Defense Successful!</span>
                        <span className="text-xs text-text-secondary">Strict cryptographical verification rules matched perfectly. Attacker's token extraction request was successfully blocked.</span>
                      </div>
                    </div>
                  ) : (
                    <div className="bg-status-danger/10 text-status-danger border border-status-danger/35 p-4 rounded-xl flex items-start gap-3">
                      <ShieldAlert className="w-5 h-5 text-status-danger shrink-0 mt-0.5 animate-bounce" />
                      <div>
                        <span className="font-extrabold text-sm block">Vulnerability Exploited!</span>
                        <span className="text-xs text-text-secondary">Breach finalized. Captured Credentials: <code className="bg-bg-nested font-mono text-[11px] px-1 rounded text-status-danger">{attackerReceivedToken}</code>. Attacker has hijacked API authentication bounds!</span>
                      </div>
                    </div>
                  )
                )}

                {victimLinkedToAttacker !== null && (
                  victimLinkedToAttacker ? (
                    <div className="bg-status-danger/10 text-status-danger border border-status-danger/35 p-4 rounded-xl flex items-start gap-3">
                      <ShieldAlert className="w-5 h-5 text-status-danger shrink-0 mt-0.5 animate-bounce" />
                      <div>
                        <span className="font-extrabold text-sm block">Account Session Hijacked!</span>
                        <span className="text-xs text-text-secondary">The victim's local state has successfully linked the attacker's third-party provider, effectively granting the attacker continuous access over the resource pipeline.</span>
                      </div>
                    </div>
                  ) : (
                    <div className="bg-status-success/15 text-status-success border border-status-success/30 p-4 rounded-xl flex items-start gap-3">
                      <ShieldCheck className="w-5 h-5 text-status-success shrink-0 mt-0.5 animate-bounce" />
                      <div>
                        <span className="font-extrabold text-sm block">CSRF Account Hijack Prevented!</span>
                        <span className="text-xs text-text-secondary">State parameter verification blocked processing of the malicious callback since it wasn't triggered within the active browser's context.</span>
                      </div>
                    </div>
                  )
                )}
              </div>
            </div>

            {/* Simulated shell terminal */}
            <div className="border border-border-subtle bg-bg-nested rounded-lg p-3 font-mono text-xs text-text-primary h-40 overflow-y-auto mt-4">
              <div className="flex items-center gap-1.5 border-b border-border-subtle pb-1.5 mb-1.5 text-[10px] text-text-muted font-bold uppercase tracking-wider">
                <Terminal className="w-3.5 h-3.5" /> Transaction Console Outputs
              </div>
              {attackLogs.length === 0 ? (
                <span className="text-text-muted italic select-none">Console ready. Trigger an exploit step to record trace traffic logs.</span>
              ) : (
                attackLogs.map((log, index) => (
                  <div key={index} className="leading-relaxed text-text-secondary">
                    {log}
                  </div>
                ))
              )}
            </div>
          </div>
        </div>

      </div>

      {/* Info Section / Architectural Guide */}
      <div className="p-6 max-w-7xl mx-auto pt-0">
        <div className="bg-bg-card border border-border-subtle rounded-xl p-6 shadow-lg">
          <h2 className="text-base font-bold text-text-primary mb-3 flex items-center gap-1.5">
            <HelpCircle className="text-status-danger w-5 h-5" /> OAuth/OIDC Exploitation Vectors & Defensive Code
          </h2>

          <div className="grid grid-cols-1 md:grid-cols-2 gap-6 text-xs text-text-secondary leading-relaxed">
            <div>
              <h3 className="font-bold text-status-danger mb-1.5 text-sm">Exploit Details</h3>
              <p className="mb-3">
                1. **PKCE Bypass:** Historically, authorization codes were redeemed on backchannels with only `client_secret` checks. On mobile apps, the secret couldn't be kept secure, so it was omitted. Without a proof key, any app that intercepted the callback query parameters (`?code=`) could exchange it for a token.
              </p>
              <p className="mb-3">
                2. **Wildcard Redirection:** In early developer portals, managers permitted whitelisting domain wildcards like `https://example.com/*` to speed up testing. This allowed attackers to input open-redirect links as the `redirect_uri` target.
              </p>
              <p>
                3. **CSRF State Hijacking:** Without state hashing, a victim clicking a forged callback link swaps their security session data context directly with attacker-controlled tokens.
              </p>
            </div>

            <div>
              <h3 className="font-bold text-status-success mb-1.5 text-sm">Remediation Strategies (JS/Node)</h3>
              <div className="space-y-3">
                <div className="bg-bg-nested p-3 rounded-lg border border-border-subtle font-mono text-[11px] relative">
                  <button 
                    onClick={() => handleCopy(`// Strict Redirect URI Check\nconst registeredUri = "https://aboutiam.com/callback";\nif (incomingUri !== registeredUri) {\n  throw new Error("Unauthorized redirect_uri");\n}`, 'rem-1')}
                    className="absolute top-2 right-2 p-1 hover:bg-bg-card rounded text-text-muted hover:text-text-primary transition"
                  >
                    {copiedText === 'rem-1' ? <Check className="w-3.5 h-3.5 text-status-success" /> : <Copy className="w-3.5 h-3.5" />}
                  </button>
                  <span className="block text-[10px] font-bold text-status-success uppercase mb-1">Strict Exact Redirect Check</span>
                  <code>{`const registered = "https://aboutiam.com/callback";
if (incoming !== registered) {
  throw new Error("Unauthorized redirect_uri");
}`}</code>
                </div>

                <div className="bg-bg-nested p-3 rounded-lg border border-border-subtle font-mono text-[11px] relative">
                  <button 
                    onClick={() => handleCopy(`// State/CSRF Session Check\nif (session.state !== incomingState) {\n  throw new Error("CSRF State Match Failed!");\n}`, 'rem-2')}
                    className="absolute top-2 right-2 p-1 hover:bg-bg-card rounded text-text-muted hover:text-text-primary transition"
                  >
                    {copiedText === 'rem-2' ? <Check className="w-3.5 h-3.5 text-status-success" /> : <Copy className="w-3.5 h-3.5" />}
                  </button>
                  <span className="block text-[10px] font-bold text-status-success uppercase mb-1">CSRF Session Verification</span>
                  <code>{`if (session.state !== incomingState) {
  throw new Error("CSRF Verification Failed!");
}`}</code>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  )
}
