import { writeFileSync, existsSync } from 'node:fs'
import { join, dirname } from 'node:path'
import { fileURLToPath } from 'node:url'
import { ROUTE_META } from '../src/routeMeta.ts'

const __filename = fileURLToPath(import.meta.url)
const __dirname = dirname(__filename)

const SITE_URL = 'https://www.aboutiam.com'

export interface SitemapUrl {
  loc: string
  changefreq: 'daily' | 'weekly' | 'monthly'
  priority: string
}

/**
 * Derives changefreq/priority from a route's path depth so every route in
 * ROUTE_META (the same registry driving live meta tags and SSG pages) gets a
 * sitemap entry automatically — no manual list to fall out of sync.
 */
export function buildSitemapUrls(routes: typeof ROUTE_META): SitemapUrl[] {
  const seen = new Set<string>()
  const urls: SitemapUrl[] = []

  for (const route of routes) {
    const normalizedPath = route.path === '/' ? '' : route.path.replace(/\/+$/, '')
    const loc = `${SITE_URL}${normalizedPath}/`
    if (seen.has(loc)) continue
    seen.add(loc)

    const depth = normalizedPath.split('/').filter(Boolean).length

    let changefreq: SitemapUrl['changefreq']
    let priority: string
    if (route.path === '/') {
      changefreq = 'daily'
      priority = '1.0'
    } else if (depth === 1) {
      changefreq = 'weekly'
      priority = '0.8'
    } else {
      changefreq = 'monthly'
      priority = '0.6'
    }

    urls.push({ loc, changefreq, priority })
  }

  return urls
}

export function buildSitemapXml(routes: typeof ROUTE_META, buildDate: Date = new Date()): { sitemapXml: string; totalCount: number } {
  const urls = buildSitemapUrls(routes)
  const lastmod = buildDate.toISOString().slice(0, 10)

  const sitemapXml = `<?xml version="1.0" encoding="UTF-8"?>
<!-- Build-generated by scripts/generate-sitemap.ts from src/routeMeta.ts — do not hand-edit. -->
<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">
${urls.map(u => `  <url>
    <loc>${u.loc}</loc>
    <lastmod>${lastmod}</lastmod>
    <changefreq>${u.changefreq}</changefreq>
    <priority>${u.priority}</priority>
  </url>`).join('\n')}
</urlset>
`

  return { sitemapXml, totalCount: urls.length }
}

// Self-execute if run directly via node command line
if (process.argv[1] && process.argv[1].endsWith('generate-sitemap.ts')) {
  try {
    const { sitemapXml, totalCount } = buildSitemapXml(ROUTE_META)

    // Write to public/sitemap.xml (acts as the repository source of truth & dev fallback)
    const publicPath = join(__dirname, '../public/sitemap.xml')
    writeFileSync(publicPath, sitemapXml, 'utf8')
    console.log(`✓ Sitemap generated successfully at: public/sitemap.xml (${totalCount} URLs)`)

    // Write to dist/sitemap.xml (if dist directory exists during standard production builds)
    const distDir = join(__dirname, '../dist')
    if (existsSync(distDir)) {
      const distPath = join(distDir, 'sitemap.xml')
      writeFileSync(distPath, sitemapXml, 'utf8')
      console.log(`✓ Sitemap copied to build output: dist/sitemap.xml`)
    }
  } catch (error) {
    console.error('💥 Failed to generate sitemap:', error)
    process.exit(1)
  }
}
