// Kept in sync with scripts/postbuild-ssg.mjs (that script can't cheaply import
// TypeScript at build time, so it keeps its own plain-JS copy of this table).
export interface RouteMeta {
  path: string
  title: string
  description: string
}

export const ROUTE_META: RouteMeta[] = [
  { path: '/', title: 'AboutIAM Overview Dashboard', description: 'Interactive Identity and Access Management (IAM) learning platform — track your progress across IAM Academy courses, playgrounds, and security tools.' },
  { path: '/primer', title: 'IAM for Beginners — What Is Identity & Access Management?', description: 'A plain-English introduction to Identity and Access Management: Identify, Authenticate, Authorize, Audit — no prior security background required.' },
  { path: '/roadmap', title: 'IAM Learning Roadmap — Zero to Hero Pathway', description: 'A guided, chronological learning sequence connecting every AboutIAM course track, from IAM fundamentals to Zero Trust architecture.' },
  { path: '/learn', title: 'IAM Academy — Free Identity & Access Management Courses', description: '6 course tracks and 36 modules covering OAuth, SAML, SCIM, Zero Trust, and PAM, with persisted completion progress and role-based recommendations.' },
  { path: '/architecture', title: 'IAM Reference Architecture Center — 24 Identity Diagrams', description: '24 clickable, beginner-to-advanced reference identity architectures — from basic session login and LDAP bind auth up through Zero Trust, B2B SaaS, and Multi-Cloud SPIFFE/SPIRE — each with threat models and simulated handshake traces.' },
  { path: '/vendor', title: 'IAM Vendor Comparison — Okta, Entra, Keycloak & More', description: '18 comprehensive enterprise IAM vendor deep-dives: Microsoft Entra, Okta, Keycloak, CyberArk, Ping Identity, ForgeRock, SailPoint, Saviynt, WSO2, AWS, GCP, Oracle, Auth0, and more — architectures, certifications, deployment checklists, and interview questions.' },
  { path: '/research', title: 'Identity CVE Database & RFC Registry — IAM Security Research', description: 'Track 13 critical identity CVEs (Log4Shell, Zerologon, JWT alg:none) with vulnerable/secure code patches, plus a 17-entry OAuth, OIDC, and SCIM RFC registry.' },
  { path: '/patterns', title: 'IAM Design Pattern Library — B2B SSO, Token Exchange & FIDO2', description: 'Production-grade integration patterns, tradeoffs, and checklists for B2B multi-tenant SaaS, API token exchange (RFC 8693), and passwordless FIDO2.' },
  { path: '/certifications', title: 'IAM Certifications Guide — SC-300, CISSP, CyberArk & More', description: '27 beginner-to-advanced identity, cloud, PAM, IGA, privacy, and GRC certifications — SC-900/SC-300/AZ-500, Okta, Ping, CyberArk, SailPoint, CISSP, CCSP, CISM — with study blueprints and mock practice quizzes.' },
  { path: '/bulletins', title: 'Identity Security Bulletins — Real-World IAM Breach Playbooks', description: '18 incident bulletins on credential theft, MFA push fatigue, OAuth abuse, and Kerberos attacks, each paired with a hands-on Crisis Response simulator.' },
  { path: '/playground', title: 'IAM Playgrounds — Free Interactive Security Simulators', description: 'Hands-on OAuth, SAML, JWT, FIDO2, Kerberos, and Zero Trust simulators — learn identity security by attacking and defending live in your browser.' },
  { path: '/tools', title: 'Free Client-Side IAM & Security Tools', description: '34 free, 100% browser-based identity and security utilities — JWT, SAML, X.509, bcrypt, TOTP, PKCE, and more. No signup, no uploads, nothing leaves your device.' },
  { path: '/tools/jwt-decoder', title: 'JWT Decoder — Inspect & Verify Tokens Online', description: 'Paste any JSON Web Token to instantly decode its header, payload, and signature, check expiry, and flag insecure algorithms — 100% client-side, nothing is uploaded.' },
  { path: '/tools/jwt-generator', title: 'JWT Generator — Build & Sign Tokens (HS256/RS256)', description: 'Create and cryptographically sign JSON Web Tokens with custom claims using HS256, HS384, HS512, or RS256 — computed locally with the Web Crypto API.' },
  { path: '/tools/base64-encoder-decoder', title: 'Base64 & Base64URL Encoder / Decoder', description: 'Encode or decode text, JSON, and files to Base64 or URL-safe Base64 (used by JWTs) instantly in your browser — no data ever leaves your device.' },
  { path: '/tools/sha256-hash-generator', title: 'SHA-256 & Hash Generator — Text and File Checksums', description: 'Generate SHA-1, SHA-256, SHA-384, and SHA-512 hashes for text or files directly in your browser using the Web Crypto API — no uploads, ever.' },
  { path: '/tools/hmac-generator', title: 'HMAC Generator & Verifier (SHA-256/SHA-1/SHA-512)', description: 'Compute and verify HMAC signatures with a shared secret key using SHA-1, SHA-256, or SHA-512 — the same primitive that signs your JWTs, run locally.' },
  { path: '/tools/uuid-generator', title: 'UUID & ULID Generator (v4, v7, Bulk)', description: 'Generate cryptographically random UUIDv4, time-sortable UUIDv7, or ULID identifiers in bulk, with one-click copy — 100% client-side randomness.' },
  { path: '/tools/password-generator', title: 'Password Generator & Entropy Strength Checker', description: 'Generate strong random passwords or passphrases with custom rules, and see the exact entropy bits and estimated crack time — computed locally.' },
  { path: '/tools/oauth-pkce-generator', title: 'OAuth PKCE Code Generator (code_verifier / code_challenge)', description: 'Generate an RFC 7636-compliant PKCE code_verifier and S256 code_challenge, and build a full OAuth 2.0 authorization URL — no backend required.' },
  { path: '/tools/totp-generator', title: 'TOTP Generator & Verifier (RFC 6238 Authenticator Codes)', description: 'Generate live, time-based one-time passwords (TOTP) from any Base32 secret and verify 6-digit codes — the same algorithm behind Google Authenticator.' },
  { path: '/tools/ldap-filter-builder', title: 'LDAP Filter Builder — Visual RFC 4515 Query Composer', description: 'Compose valid LDAP search filters visually with AND/OR/NOT groups, then copy the exact RFC 4515 filter string — no directory connection needed.' },
  { path: '/tools/scim-payload-validator', title: 'SCIM Payload Validator & Builder (RFC 7643/7644)', description: 'Validate or scaffold SCIM 2.0 User and Group JSON payloads against the core schema, with inline errors for missing or malformed attributes.' },
  { path: '/tools/basic-auth-decoder', title: 'Basic & Bearer Auth Header Decoder', description: 'Decode HTTP Basic Authentication headers to reveal the username/password, or inspect Bearer tokens — a quick, private, client-side debugging utility.' },
  { path: '/tools/jwk-pem-converter', title: 'JWK to PEM Converter (and back) + Thumbprint', description: 'Convert RSA/EC JSON Web Keys (JWK) to PEM format and back, and compute the RFC 7638 JWK thumbprint — all cryptography runs in your browser.' },
  { path: '/tools/x509-certificate-decoder', title: 'X.509 Certificate Decoder — Parse PEM Certs & CSRs', description: 'Decode X.509 certificates and PKCS#10 CSRs to view subject, issuer, validity dates, SANs, key usage, and fingerprints — parsed locally, never uploaded.' },
  { path: '/tools/saml-decoder', title: 'SAML Decoder — Inspect SAMLRequest/Response & Metadata', description: 'Decode Base64/deflate-encoded SAMLRequest and SAMLResponse parameters, or pretty-print SP/IdP metadata XML — no server round-trip, fully client-side.' },
  { path: '/tools/saml-metadata-builder', title: 'SAML Metadata Builder — Generate SP & IdP Metadata XML', description: 'Visually configure compliant SAML 2.0 Service Provider (SP) or Identity Provider (IdP) XML metadata configurations, endpoints, certificates, and export completed files.' },
  { path: '/tools/scim-diff', title: 'SCIM Diff & Reconciliation Tool — Calculate Sync Drift', description: 'Input Identity Provider (IdP) and Service Provider (SP) user records to visually calculate attribute sync drift and programmatically generate standard-compliant SCIM PATCH reconciliation scripts.' },
  { path: '/tools/csr-generator', title: 'X.509 CSR Generator — Compile PKCS#10 Requests Online', description: 'Visually construct secure X.509 Certificate Signing Requests (CSR) with Subject DN attributes and SAN fields, generate browser-native private/public keys, and inspect their ASN.1 DER-parsed structure.' },
  { path: '/tools/sd-jwt-decoder', title: 'SD-JWT Decoder — Selective Disclosure JWT Inspector', description: 'Decode Selective Disclosure JWTs (SD-JWT), reveal individual disclosures, and verify each digest binding against the issuer-signed JWT — entirely in-browser.' },
  { path: '/tools/webauthn-decoder', title: 'WebAuthn / Passkey Assertion & Attestation Decoder', description: 'Decode clientDataJSON, authenticatorData, and CBOR attestationObject from a WebAuthn credential to inspect flags, counters, and public keys.' },
  { path: '/tools/did-key-generator', title: 'DID Generator — Create a did:key Identifier', description: 'Generate an Ed25519 keypair entirely in your browser and derive its did:key decentralized identifier and DID document — no wallet, no blockchain.' },
  { path: '/tools/bcrypt-generator', title: 'bcrypt Hash Generator & Verifier Online', description: 'Hash passwords with bcrypt at a custom cost factor, or verify a password against an existing bcrypt hash — computed entirely client-side, in pure JavaScript.' },
  { path: '/tools/oauth-builder', title: 'OAuth 2.0 / OIDC Request Builder & Handshake Debugger', description: 'Visually construct standard-compliant OAuth 2.0 and OpenID Connect authorization URLs and token exchange payloads.' },
  { path: '/tools/jwks-inspector', title: 'JWKS JSON Web Key Set Inspector', description: 'Parse, inspect, and validate public JSON Web Key Sets (JWKS) representing cryptographic signing keys used for JWT verification.' },
  { path: '/tools/policy-evaluator', title: 'ABAC & RBAC Client-Side Policy Evaluator', description: 'An interactive sandbox to evaluate custom JSON-based access policies against simulated user, device, and resource contexts.' },
  { path: '/tools/passphrase-entropy', title: 'Diceware Passphrase & Entropy Strength Calculator', description: 'Compare standard character-shuffled passwords against word-based dictionary passphrases to calculate mathematical entropy bits and offline GPU cracking times.' },
  { path: '/tools/oidc-discovery', title: 'OIDC Discovery Document Auditor', description: 'Parse, visualize, and audit modern Identity Provider metadata profiles containing standard OIDC endpoint registries.' },
  { path: '/tools/ansible-vault', title: 'Ansible Vault Encryptor & Decryptor', description: 'Encrypt or decrypt secrets client-side using the standard Ansible Vault 1.1/1.2 AES-256 cipher format — 100% browser-native PBKDF2 + AES-CTR + HMAC-SHA256.' },
  { path: '/tools/sops-simulator', title: 'Mozilla SOPS — GitOps Secrets Simulator', description: 'An interactive envelope encryption playground. Selectively encrypt configuration values in YAML or JSON files using simulated AWS KMS, Azure Key Vault, or Age keys, preserving key paths for Git diffs.' },
  { path: '/playground/jwt', title: 'JWT Playground — Sign, Crack & Exploit Tokens Live', description: 'Sign real HS256 JSON Web Tokens in your browser, then exploit the alg:none bypass and JWKS-spoofing vulnerabilities hands-on.' },
  { path: '/playground/oauth', title: 'OAuth 2.0 & OIDC Flow Visualizer — Step-by-Step Simulator', description: 'Watch a real OAuth 2.0 / OpenID Connect authorization code flow unfold step-by-step with PKCE, animated redirects, and raw HTTP inspection.' },
  { path: '/playground/saml', title: 'SAML 2.0 Playground — XML Assertions & Signature Wrapping', description: 'Build SAML assertions and launch a live Signature Wrapping (SSW) attack against a mock Service Provider — entirely in your browser.' },
  { path: '/playground/fido2', title: 'FIDO2 & WebAuthn Playground — Passkey Registration Simulator', description: 'Emulate a full FIDO2/WebAuthn passkey registration and login ceremony, parsing real clientDataJSON and authenticatorData bytes.' },
  { path: '/playground/access', title: 'ABAC vs RBAC Playground — Access Control Policy Simulator', description: 'Evaluate live attribute-based (ABAC) and role-based (RBAC) access decisions side-by-side against device, location, and department context.' },
  { path: '/playground/ldap', title: 'LDAP Playground — Active Directory Filter Simulator', description: 'Search a simulated Active Directory tree with real RFC 4515 LDAP filters and watch matching nodes highlight instantly.' },
  { path: '/playground/zta', title: 'Zero Trust Playground — NIST SP 800-207 Risk Planner', description: 'Model a NIST SP 800-207 Zero Trust risk-scoring engine and see how device, network, and identity signals change access outcomes live.' },
  { path: '/playground/scim', title: 'SCIM Playground — User Provisioning Sync Simulator', description: 'Simulate real-time SCIM 2.0 user and group provisioning between an Identity Provider and Service Provider, including 429/409 sync conflicts.' },
  { path: '/playground/oauth-attack', title: 'OAuth 2.0 Attack Lab — PKCE Bypass & Redirect Hijack Playground', description: 'Hack and defend a mock OAuth 2.0 flow: exploit PKCE downgrade, wildcard redirect URIs, and CSRF state omission, then patch each vulnerability.' },
  { path: '/playground/kerberos', title: 'Kerberos Playground — Golden & Silver Ticket Attack Simulator', description: 'Walk through a full Kerberos AS/TGS ticket exchange, then forge Golden and Silver Tickets against a simulated Active Directory domain.' },
  { path: '/playground/ctf', title: 'Identity CTF Arena — Free IAM Hacking Challenges', description: 'Solve browser-native capture-the-flag challenges covering JWT bypasses, SAML wrapping injections, and LDAP filter escapes, with a live scoreboard.' },
  { path: '/playground/identity-architect', title: 'AI Identity Architect — Generate IAM Blueprints Instantly', description: "Answer a few questions about your organization and generate a bespoke, compliance-ready identity architecture, threat model, and OPA policy." },
  { path: '/playground/jwt-cracker', title: 'JWT Cracker — HMAC Secret Dictionary Attack Simulator', description: 'Watch a client-side dictionary attack recover a weak HS256 JWT signing secret in seconds, and learn why short shared secrets are dangerous.' },
  { path: '/playground/cert-chain', title: 'mTLS & Certificate Chain Playground — PKI Trust Simulator', description: 'Build a Root → Intermediate → Leaf Certificate Authority chain, then simulate real-time OCSP and CRL revocation checks and mTLS handshakes.' },
  { path: '/playground/gpo-simulator', title: 'Active Directory GPO Simulator — Password Policy Playground', description: 'Configure Default Domain GPO password length, lockout thresholds, and Kerberos ticket lifetimes, then watch simulated logon lockouts play out.' },
  { path: '/playground/reference-builder', title: 'Enterprise IAM Architecture Builder — Drag & Drop Designer', description: 'Drag and drop identity components to design an enterprise topology, with animated OIDC, SAML, and SCIM handshake traces between them.' },
  { path: '/playground/session-hijacking', title: 'Session Hijacking Playground — Token Theft & DPoP Defense Lab', description: 'Simulate an infostealer stealing a session cookie, then compare how DPoP, IP-binding, and CAEP each stop the replayed token from working.' },
  { path: '/playground/conditional-access', title: 'Conditional Access Playground — Policy Simulator', description: 'Evaluate simulated sign-in requests against device compliance, network, geolocation, and risk-score conditional access policies.' },
  { path: '/playground/opa', title: 'Open Policy Agent (OPA) & Rego Playground — Live Policy Editor', description: 'Write real Rego authorization rules against custom input JSON and trace how the OPA policy engine evaluates each decision.' },
  { path: '/playground/token-exchange', title: 'Token Exchange Playground — RFC 8693 STS Simulator', description: 'Model a Security Token Service broker exchanging an incoming token for a scoped, delegated, or impersonated downstream access token.' },
  { path: '/playground/itdr', title: 'ITDR Playground — Identity Threat Detection Simulator', description: 'Monitor a live authentication log stream, inject brute-force and push-fatigue attacks, and trigger automated lockout countermeasures.' },
  { path: '/playground/device-trust', title: 'Device Posture Playground — Zero Trust Attestation Simulator', description: 'Simulate a Zero Trust device-posture handshake checking firewall state, disk encryption, OS version, and client certificates before granting access.' },
  { path: '/playground/passkey-internals', title: 'Passkey Internals Playground — WebAuthn Byte-Level Explorer', description: 'Deconstruct the raw authenticatorData byte offsets and CBOR public keys a hardware TPM generates during passkey registration.' },
  { path: '/playground/ai-threat-lab', title: 'AI Deepfake vs MFA Playground — Voice Spoofing Simulator', description: 'Simulate an AI voice-deepfake attack against legacy phone-based MFA and see why FIDO2 hardware-bound credentials resist it.' },
  { path: '/playground/zkp-wallet', title: 'Zero-Knowledge Proof Wallet — Age Verification Playground', description: 'Generate a real zero-knowledge proof that verifies you are over an age threshold without ever revealing your actual birthdate.' },
  { path: '/playground/ambient-trust', title: 'Ambient Trust Playground — Continuous Authentication Simulator', description: 'Watch a session trust score decay and recover in real time as simulated keystroke and location telemetry signals change.' },
  { path: '/playground/workload-mesh', title: 'SPIFFE/SPIRE Playground — Workload Identity Simulator', description: 'Issue dynamic X.509 SVID credentials between simulated microservices and see how workload identity replaces static API keys.' },
  { path: '/playground/xacml', title: 'XACML 3.0 Playground — Policy Combining Algorithm Engine', description: 'Evaluate real XACML 3.0 rules and compare deny-overrides, permit-overrides, first-applicable, and only-one-applicable combining algorithms live.' },
  { path: '/playground/gnap', title: 'GNAP Playground — Grant Negotiation Protocol Visualizer', description: 'Step through an RFC 9635 GNAP grant request, user interaction, continuation, and key-bound token issuance timeline.' },
  { path: '/playground/caep', title: 'CAEP Playground — Continuous Access Evaluation Simulator', description: 'Push signed Security Event Tokens between a transmitter and receiver to see how CAEP revokes sessions and reacts to risk changes in real time.' },
  { path: '/playground/vc-did', title: 'Verifiable Credentials & DID Playground — Issuer/Holder/Verifier Flow', description: 'Issue, hold, and verify a real Ed25519 Verifiable Credential and Presentation entirely in your browser.' },
  { path: '/explore/matchmaker', title: 'Auth Matchmaker — Find Your Ideal Authentication Stack', description: 'Answer a short wizard and get a recommended authentication stack with copyable boilerplate code for your exact requirements.' },
  { path: '/assess', title: 'GRC Maturity Assessment — Free IAM Readiness Self-Test', description: 'A 5-pillar Identity Governance, Risk & Compliance maturity self-assessment with dynamic charts and an exportable roadmap.' },
  { path: '/tools/key-ring', title: 'Hardware Key Ring & HSM Emulator', description: 'Generate, store, and execute asymmetric and symmetric cryptographic keys locally inside your browser\'s secure sandbox — emulating a corporate Hardware Security Module (HSM).' },
  { path: '/tools/conformance-checker', title: 'Standards Conformance Checker', description: 'Paste an OIDC discovery document or SAML 2.0 metadata XML and run an automated pass/fail checklist against required fields and structural rules — 100% client-side.' },
  { path: '/tools/pbkdf2-generator', title: 'PBKDF2 Key Derivation & Hash Verifier', description: 'Derive a key from a password using PBKDF2 with a configurable salt, iteration count, and hash function, and verify a password against a stored derived hash — all via the Web Crypto API.' },
  { path: '/tools/cert-bundle-splitter', title: 'PEM Certificate Bundle Splitter & Chain Order Checker', description: 'Paste a multi-certificate PEM bundle to split it into individual certificates, inspect each one\'s subject/issuer/expiry, and check whether the leaf-to-root chain order is correct.' },
  { path: '/tools/did-document-validator', title: 'DID Document Validator & Resolver Preview', description: 'Paste a Decentralized Identifier (DID) Document JSON and validate it against the W3C DID Core structural requirements, with a pretty-printed, field-by-field resolved preview.' },
  { path: '/playground/identity-broker', title: 'Identity Broker Playground — Multi-Tenant SSO Federation Simulator', description: 'Explore multi-tenant single sign-on routing and real-time SAML-to-OIDC token translation across a federated identity broker.' },
  { path: '/playground/magic-link-stepup', title: 'Magic Link & Step-Up Auth Playground — Passwordless Simulator', description: 'Log in with a passwordless email magic link, then trigger a forced step-up to WebAuthn or OTP before completing a high-risk action.' },
  { path: '/playground/credential-stuffing', title: 'Credential Stuffing Defense Playground — Password Spray Simulator', description: 'Replay leaked credentials against a mock login and toggle rate-limiting, CAPTCHA, breached-password detection, and lockout defenses to stop them.' },
  { path: '/playground/ciam-consent', title: 'CIAM Consent Playground — Social Login & Progressive Profiling', description: 'Simulate a social login consent screen, OAuth scope grants, and progressive profile-field collection across multiple sessions.' },
  { path: '/playground/access-certification', title: 'Access Certification Playground — SoD Review Simulator', description: 'Review simulated user-to-entitlement access rows, approve or revoke access, and flag Separation-of-Duties conflicts like a real IGA campaign.' },
  { path: '/playground/risk-engine', title: 'Risk-Based Authentication Playground — Adaptive MFA Simulator', description: 'Combine impossible-travel, device-reputation, and behavior-anomaly signals into a composite risk score that drives allow, step-up, or block.' },
  { path: '/playground/pam-vaulting', title: 'PAM Vaulting Playground — Just-in-Time Elevation Simulator', description: 'Check out a vaulted credential, request time-boxed JIT elevation with approval, and watch session recording and auto-rotation on check-in.' },
  { path: '/playground/hybrid-ad-sync', title: 'Hybrid Identity Sync Playground — PHS vs PTA vs Federation', description: "Toggle between Password Hash Sync, Pass-Through Authentication, and AD FS Federation to see how each handles the same on-prem login." },
  { path: '/career-center', title: 'IAM Interview Prep & Career Center — 6 Role Tracks', description: 'Role-based interview preparation from Fresher to Principal, with MCQs, incident scenarios, system design audits, and resume guidance.' },
  { path: '/scenario-builder', title: 'Identity Scenario Builder — Custom Architecture Generator', description: "Describe your organization's footprint and get an instant, vendor-neutral secure identity architecture blueprint." },
  { path: '/labs', title: 'Interactive Identity Labs — Hands-On IAM Pen-Test Academy', description: 'Solve real OAuth, JWT, SAML, and SCIM security vulnerabilities in a browser-native penetration-testing sandbox.' },
  { path: '/references', title: 'Enterprise IAM Reference Implementations — Copyable Code', description: 'Categorized, beginner-to-advanced library of production-quality, copyable IAM reference code — session auth, LDAP, OAuth/OIDC, WebAuthn, SCIM, OPA/Rego, Vault, cloud workload identity, Kubernetes RBAC, and Istio mTLS.' },
  { path: '/case-studies', title: 'IAM Case Studies — Netflix, Uber, Cloudflare & More', description: '13 real-world, production-quality IAM implementation case studies across Big Tech, Financial Services, Government, and Healthcare.' },
  { path: '/decision-matrix', title: 'Identity Architecture Decision Matrix — Protocol Recommender', description: 'Interactive architecture recommendation engine mapping standard protocols, authorization schemas, IdPs, checklists, and deep-linked tools.' },
  { path: '/threat-modeling', title: 'IAM Threat Modeling Studio — STRIDE & MITRE ATT&CK Simulator', description: 'Visually build an IAM architecture and run threat analysis against STRIDE, MITRE ATT&CK, and OWASP, with dynamic risk scores and mitigation reports.' },
  { path: '/design-review', title: 'IAM Design Review Assistant — OAuth, SAML & JWT Auditor', description: 'Interactive design reviewer executing automated structural audits on OAuth parameters, SAML XML, and JWT payload configurations.' },
  { path: '/standards', title: 'IAM Standards & RFC Explorer — OAuth, SAML, SCIM, WebAuthn', description: '19 living identity standards with visual specifications and RFC timelines across OAuth, OpenID Connect, SCIM, SAML, and WebAuthn.' },
  { path: '/events', title: 'IAM Events & Conferences', description: 'Upcoming Identity and Access Management conferences and summits — EIC, Identiverse, Gartner IAM Summit, Authenticate, RSA Conference, and KuppingerCole Impact Days — with dates, locations, and official links.' },
  { path: '/reports', title: 'IAM Analyst Reports & Research', description: 'Curated abstracts, named leaders, and a cross-analyst leaderboard from the Gartner Magic Quadrant, Forrester Wave, and KuppingerCole Leadership Compass reports on Access Management, PAM, and CIAM, plus Thales\'s annual Data Threat Report research.' },
  { path: '/explore', title: 'IAM Landscape Directory — Compare 21 Identity Products', description: 'Browse Open Source IdPs, Enterprise SaaS, CIAM, PAM, and Secrets Engines side-by-side, with license details and copyable integration snippets.' },
  { path: '/assistant', title: 'AI IAM Assistant — Knowledge Chat, Comparisons & Interview Prep', description: 'Intelligent IAM platform navigator, 20 side-by-side protocol comparisons, a learning planner, and an interview prep simulator.' },
  { path: '/encyclopedia', title: 'IAM Glossary — 182 Identity & Access Management Terms Defined', description: 'A searchable A-Z encyclopedia of Identity and Access Management standards, protocols, and acronyms, each with a beginner analogy and expert spec.' },
  { path: '/timeline', title: 'Interactive Identity Timeline', description: 'An immersive, clickable, dual-themed timeline tracing the history of digital identity from 1961 mainframes to future ambient trust, with active inline simulators for each era.' },
  { path: '/community', title: 'Community Achievements & Challenges', description: 'Unlock offline contributor achievements, tackle tactical security challenges, and trace your learning progression scoreboard.' },
  { path: '/community-forums', title: 'Community Forums & Showcase', description: 'Browse expert architectural discussion boards, deconstruct hardened IAM code snippets, and federate your designed Reference Architectures.' },
  { path: '/wall-of-shame', title: 'IAM Breach Museum — 27 Real-World Identity Security Incidents', description: 'Explore historic identity breaches like Golden SAML and MFA push-bombing fatigue, each with a vulnerable-vs-secure code deconstruction.' },
  { path: '/cheat-sheets', title: 'IAM Cheat Sheets — 24 Security Compliance Checklists', description: 'Interactive hardening checklists for OAuth, SAML, JWT, Zero Trust, Kubernetes RBAC, SOC 2, HIPAA, and GDPR, with live compliance gauges.' },
  { path: '/contributors', title: 'Team & Contact', description: 'Meet the AboutIAM contributors and get in touch.' },
  { path: '/terms', title: 'Terms, License & Disclaimer', description: 'MIT license details and educational-use disclaimer for AboutIAM\'s interactive identity security labs.' },
]

const DEFAULT_META: RouteMeta = {
  path: '/',
  title: 'AboutIAM Secure Workspace',
  description: 'Open-source, 100% client-side academy and simulation workbench for Identity and Access Management.',
}

export function getRouteMeta(pathname: string): RouteMeta {
  // Real URLs (and location.pathname at runtime) always carry a trailing
  // slash (see scripts/postbuild-ssg.mjs's per-route dist/<path>/index.html
  // layout), but no ROUTE_META entry does — normalize before matching, or
  // every non-root route falls through to the prefix fallback below.
  const normalized = pathname.length > 1 ? pathname.replace(/\/+$/, '') : pathname
  const exact = ROUTE_META.find((r) => r.path === normalized)
  if (exact) return exact
  // Fall back to the longest known ancestor path, not array order — e.g.
  // '/playground/xacml' must not resolve to the earlier, shorter '/playground'
  // entry just because .find() would hit it first.
  const prefixMatches = ROUTE_META.filter((r) => r.path !== '/' && normalized.startsWith(`${r.path}/`))
  if (prefixMatches.length === 0) return DEFAULT_META
  return prefixMatches.reduce((longest, r) => (r.path.length > longest.path.length ? r : longest))
}
